# docker 

apt-get update
apt-get upgrade
apt-get dist-upgrade
apt-get install raspberrypi-ui-mods

# cloudmesh
RUN apt-get install python-gdbm
RUN pip install cloudmesh.common
RUN pip install cloudmesh.cmd5
RUN pip install cloudmesh.sys

RUN pip install ansible -y

CMD ["bash"]
